baseURL = "https://www.hux.ink/"
languageCode = "en-us"
timeZone = 'Asia/Shanghai'
title = "Counting Stars💫"
theme = "ivy"
disqusShortname = "落落vici"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/posts/:slug/"
  

[menu]
  [[menu.main]]
  name="哔哔"
  url="/bb/"
  weight="1"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="2" 
   [[menu.main]]
  name="他们"
  url="https://immmmm.com/friends/"
  weight="3"
  [[menu.main]]
  name="花园"
  url="https://clip.hux.ink/"
  weight="4"
  [[menu.main]]
  name="跑步"
  url="https://run.hux.ink//"
  weight="5"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="6"
 
  
  
  

  

[params]
  # description about this website
  description = "🌩️🌩️🌩️莫思身外无穷事，且尽生前有限杯。"
  footer = "&copy; [Counting Stars💫](https://www.hux.ink/) | since 2023"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"  

  

[params.twikoo]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[outputs]
  home = ["HTML","RSS","JSON"] # <domain>/atom.xml
  page = ["HTML"]