baseURL = "https://hux.ink/"
languageCode = "en-us"
timeZone = 'Asia/Shanghai'
title = "Counting Stars💫"
theme = "ivy"
disqusShortname = "落落vici"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/posts/:slug/"
  

[menu]
  [[menu.main]]
  name="哔哔"
  url="/bb/"
  weight="1"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="2" 
  [[menu.main]]
  name="光影"
  url="/album/"
  weight="3"  
  [[menu.main]]
  name="悦动"
  url="/exercise/"
  weight="4"
  [[menu.main]]
  name="断章"
  url="/clip/"
  weight="5"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="6"
 
  
  
  

  

[params]
  # description about this website
  description = "🌩️🌩️🌩️欲买桂花同载酒，终不似，少年游。"
  mottoPrefix = " "
  mottos = [
  "❄️ 晚来天欲雪，能饮一杯无？",
  "🏡 此心安处是吾乡。",
  "☁️ 行到水穷处，坐看云起时。",
  "🌩️ 欲买桂花同载酒，终不似，少年游。",
  "🍂 人生如逆旅，我亦是行人。",
  "⛵ 小舟从此逝，江海寄余生。",
  "🌗 当时明月在，曾照彩云归。",  
  "🌼 掬水月在手，弄花香满衣。",
  "🌧️ 一蓑烟雨任平生。",
  "🌤️ 云无心以出岫，鸟倦飞而知还。",
  "🌄 我见青山多妩媚，料青山见我应如是。",
  "✨ 山有木兮木有枝，心悦君兮君不知。",
  "🕊️ 落霞与孤鹜齐飞，秋水共长天一色。"
  ]
  footer = "&copy; [Counting Stars💫](https://hux.ink/admin) | [Since 2023](https://hux.ink/index.xml)"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"  

  

[params.twikoo]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[outputs]
  home = ["HTML","RSS","JSON"] # <domain>/atom.xml
  page = ["HTML"]
