baseURL = "https://www.huxin1216.xyz/"
languageCode = "en-us"
timeZone = 'Asia/Shanghai'
title = "Counting Stars💫"
theme = "ivy"
disqusShortname = "cos0"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/posts/:slug/"
  

[menu]
  [[menu.main]]
  name="哔哔"
  url="/bb/"
  weight="1"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="2" 
  [[menu.main]]
  name="光影"
  url="/album/"
  weight="3"
  [[menu.main]]
  name="简悦"
  url="https://clip.hux.ink/"
  weight="4"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="5"
 
  
  
  

  

[params]
  # description about this website
  description = "🌩️🌩️🌩️莫思身外无穷事，且尽生前有限杯。"
  footer = "&copy; [Counting Stars💫](https://www.huxin1216.xyz/) | since 2023"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"  

  

[params.twikoo]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[outputs]
  home = ["HTML","RSS","JSON"] # <domain>/atom.xml
  page = ["HTML"]